'use client';

import { useState, useEffect } from 'react';
import type { Message } from '@/lib/chat-store';
import {
  useExtractedTopics,
  useSyntheticSummary,
  useInsightGeneration,
  useDragResize,
  type Insight,
} from './useSideMiniChatLogic';

interface SideMiniChatProps {
  isVisible?: boolean;
  messages: Message[];
  onSendQuery?: (query: string) => void;
  externalQuery?: string; // NEW: For Deep Dive button to inject queries
  conversationId?: string; // NEW: For sharing conversation
  onPromoteToMain?: (query: string, response: string) => void; // NEW: Bidirectional sync
  draggable?: boolean; // When true (canvas mode), allows drag-to-move
  defaultPosition?: { left: number; top: number }; // Starting position when draggable
  /** When true, suppress the synthetic summary + LINKS sections — assumes CanvasSynthesisDrawer owns that content. */
  hideSynopsis?: boolean;
}

/**
 * Enhanced Side Mini Chat
 *
 * Shows for every query:
 * - Input field for direct queries
 * - 3-line synthetic explanation (topics + progress + insights)
 * - Pertinent links based on actual query content
 * - Context-aware suggestions
 */
export default function SideMiniChat({
  isVisible = true,
  messages = [],
  onSendQuery,
  externalQuery,
  conversationId,
  onPromoteToMain,
  draggable = false,
  defaultPosition,
  hideSynopsis = false,
}: SideMiniChatProps) {
  const [inputText, setInputText] = useState('');
  const [miniChatMessages, setMiniChatMessages] = useState<{ query: string; response: string }[]>(
    []
  );
  const [isMiniLoading, setIsMiniLoading] = useState(false);
  const [showShareToast, setShowShareToast] = useState(false);

  // Extracted hooks
  const extractedTopics = useExtractedTopics(messages);
  const syntheticSummary = useSyntheticSummary(messages);
  const { insights, metacognition } = useInsightGeneration(messages, extractedTopics);
  const { dragPos, isDragging, handleDragStart, chatSize, isResizing, handleResizeStart } =
    useDragResize(draggable, defaultPosition);

  // Handle external queries (from Deep Dive button)
  useEffect(() => {
    if (externalQuery && externalQuery.trim()) {
      // Set input text for user to review/edit
      setInputText(externalQuery);
      // Note: onSendQuery will be called when user manually submits
    }
  }, [externalQuery]);

  /**
   * Handle insight click
   */
  const handleInsightClick = (insight: Insight) => {
    if (insight.type === 'link') {
      // Open link in new tab
      window.open(insight.content, '_blank', 'noopener,noreferrer');
    }
    // For suggestions, user can copy the text manually
  };

  /**
   * Share conversation summary
   */
  const handleShareSummary = async () => {
    if (messages.length === 0) return;

    const userMessages = messages.filter((m) => m.role === 'user');
    const aiMessages = messages.filter((m) => m.role === 'assistant');

    // Build shareable summary
    const summary = {
      topics: extractedTopics,
      exchanges: Math.floor(messages.length / 2),
      queries: userMessages.map((m) => m.content.substring(0, 100)),
      syntheticSummary: syntheticSummary.summary,
      conversationId: conversationId || 'none',
      timestamp: new Date().toISOString(),
    };

    // Copy to clipboard
    const shareText = `
AkhAI Conversation Summary
━━━━━━━━━━━━━━━━━━━━━━━━
Topics: ${extractedTopics.join(', ')}
Exchanges: ${summary.exchanges}
━━━━━━━━━━━━━━━━━━━━━━━━

${syntheticSummary.summary}

━━━━━━━━━━━━━━━━━━━━━━━━
Recent Queries:
${userMessages
  .slice(-3)
  .map((m, i) => `${i + 1}. ${m.content.substring(0, 80)}...`)
  .join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━
Generated by AkhAI - Sovereign Research Engine
${conversationId ? `View: ${window.location.origin}?continue=${conversationId}` : ''}
`.trim();

    try {
      await navigator.clipboard.writeText(shareText);
      setShowShareToast(true);
      setTimeout(() => setShowShareToast(false), 2000);
    } catch (error) {
      console.error('Failed to copy summary:', error);
    }
  };

  /**
   * Handle query submission from Mini Chat input
   */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || isMiniLoading) return;

    const currentQuery = inputText;
    setInputText('');
    setIsMiniLoading(true);

    // Add query to mini chat messages
    setMiniChatMessages((prev) => [...prev, { query: currentQuery, response: '...' }]);

    try {
      // Call API directly from Mini Chat (not main chat)
      const res = await fetch('/api/simple-query', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          query: currentQuery,
          methodology: 'direct',
          conversationHistory: [],
        }),
      });

      const data = await res.json();

      // Update last message with response
      setMiniChatMessages((prev) => {
        const updated = [...prev];
        updated[updated.length - 1] = {
          query: currentQuery,
          response: data.response || 'No response',
        };
        return updated;
      });
    } catch (error) {
      console.error('Mini Chat error:', error);
      setMiniChatMessages((prev) => {
        const updated = [...prev];
        updated[updated.length - 1] = {
          query: currentQuery,
          response: 'Error: Failed to get response',
        };
        return updated;
      });
    } finally {
      setIsMiniLoading(false);
    }
  };

  if (!isVisible) return null;

  // Canvas (draggable) mode: fixed position with drag handle + compact bg
  if (draggable) {
    return (
      <div
        className="fixed z-50 select-none"
        style={{ left: dragPos.left, top: dragPos.top, width: chatSize.width }}
      >
        {/* Drag handle */}
        <div
          className={`cursor-grab active:cursor-grabbing h-5 flex items-center justify-center rounded-t border border-b-0 border-relic-mist/40 bg-white/90 backdrop-blur-sm ${isDragging ? 'ring-1 ring-purple-300' : ''} ${isResizing ? 'ring-1 ring-blue-300' : ''}`}
          onMouseDown={handleDragStart}
        >
          <span className="text-[7px] text-relic-silver font-mono uppercase tracking-wider">
            ≡ side canal
          </span>
        </div>
        {/* Content with bg for canvas visibility */}
        <div
          className="relative bg-white/85 backdrop-blur-sm rounded-b border border-relic-mist/40 p-1.5 overflow-y-auto overflow-x-hidden space-y-1.5 break-words"
          style={{ maxHeight: chatSize.height - 20 }}
        >
          {/* Topics */}
          {extractedTopics.length > 0 && (
            <div className="pb-1 border-b border-relic-mist/10">
              <div className="text-[6px] text-relic-silver/40 font-mono uppercase tracking-wider mb-0.5">
                topics
              </div>
              <div className="flex flex-wrap gap-0.5">
                {extractedTopics.map((topic, idx) => (
                  <span key={idx} className="text-[7px] text-relic-slate/70 font-mono">
                    {topic}
                    {idx < extractedTopics.length - 1 ? ' ·' : ''}
                  </span>
                ))}
              </div>
            </div>
          )}
          {/* Synthetic summary (hidden when CanvasSynthesisDrawer owns synopsis content) */}
          {!hideSynopsis && syntheticSummary.summary && (
            <div className="pb-1 border-b border-relic-mist/10">
              <div className="text-[7px] text-relic-slate/80 font-mono leading-snug">
                {syntheticSummary.summary}
              </div>
            </div>
          )}
          {/* Links (hidden when CanvasSynthesisDrawer owns synopsis content) */}
          {!hideSynopsis && insights.filter((i) => i.type === 'link').length > 0 && (
            <div className="pb-1">
              <div className="text-[6px] text-relic-silver/40 font-mono uppercase tracking-wider mb-0.5">
                links
              </div>
              {insights
                .filter((i) => i.type === 'link')
                .slice(0, 3)
                .map((link) => (
                  <button
                    key={link.id}
                    onClick={() => handleInsightClick(link)}
                    className="block w-full text-left text-[7px] text-relic-slate/60 hover:text-relic-void font-mono truncate"
                  >
                    →{' '}
                    {typeof link.source === 'string' ? link.source : String(link.source || 'Link')}
                  </button>
                ))}
            </div>
          )}
          {/* Mini input */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (inputText.trim() && onSendQuery) {
                onSendQuery(inputText.trim());
                setInputText('');
              }
            }}
            className="flex gap-1"
          >
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="ask..."
              className="flex-1 text-[7px] font-mono bg-transparent border-b border-relic-mist/20 outline-none text-relic-slate placeholder:text-relic-silver/30 py-0.5"
            />
            <button
              type="submit"
              className="text-[7px] text-relic-silver hover:text-relic-void font-mono"
            >
              →
            </button>
          </form>
          {/* Resize grip */}
          <div
            className="absolute bottom-0 right-0 w-5 h-5 cursor-se-resize flex items-center justify-center text-relic-silver/40 hover:text-relic-slate"
            onMouseDown={handleResizeStart}
          >
            <svg
              width="10"
              height="10"
              viewBox="0 0 14 14"
              fill="none"
              stroke="currentColor"
              strokeWidth="1"
            >
              <line x1="4" y1="14" x2="14" y2="4" />
              <line x1="8" y1="14" x2="14" y2="8" />
              <line x1="12" y1="14" x2="14" y2="12" />
            </svg>
          </div>
        </div>
      </div>
    );
  }

  // Classic mode: original fixed overlay
  return (
    <div className="fixed left-[5%] top-[35%] bottom-[15%] w-[15%] max-w-[220px] z-50 pointer-events-none">
      {/* Invisible console - no background, no border, just raw text */}
      <div className="pointer-events-auto space-y-2 overflow-y-auto max-h-full overflow-x-hidden break-words pr-6">
        {/* Topics & Share */}
        {extractedTopics.length > 0 && (
          <div className="mb-2 pb-2 border-b border-relic-mist/10 dark:border-relic-slate/20">
            <div className="flex items-center justify-between mb-1">
              <div className="text-[7px] text-relic-silver/40 dark:text-relic-ghost/50 font-mono uppercase tracking-wider">
                topics
              </div>
              {messages.length > 0 && (
                <button
                  onClick={handleShareSummary}
                  className="text-[7px] text-relic-slate/50 dark:text-relic-ghost/50 hover:text-relic-void dark:hover:text-white font-mono transition-colors"
                  title="Copy conversation summary"
                >
                  share
                </button>
              )}
            </div>
            <div className="flex flex-wrap gap-1">
              {extractedTopics.map((topic, idx) => (
                <span
                  key={idx}
                  className="text-[7px] text-relic-slate/60 dark:text-relic-ghost/60 font-mono"
                >
                  {topic}
                  {idx < extractedTopics.length - 1 && ' •'}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Share Toast */}
        {showShareToast && (
          <div className="mb-2 text-[7px] text-green-600 dark:text-green-400 font-mono animate-fade-in">
            ✓ copied to clipboard
          </div>
        )}

        {/* 3-line Synthetic Explanation (hidden when CanvasSynthesisDrawer owns synopsis content) */}
        {!hideSynopsis && syntheticSummary.summary && (
          <div className="mb-3 pb-2 border-b border-relic-mist/10 dark:border-relic-slate/20">
            <div className="text-[8px] text-relic-slate/50 dark:text-relic-ghost/70 font-mono leading-relaxed whitespace-pre-line">
              {syntheticSummary.summary}
            </div>
          </div>
        )}

        {/* Compact Links — Raw list (hidden when CanvasSynthesisDrawer owns synopsis content) */}
        {!hideSynopsis && insights.filter((i) => i.type === 'link').length > 0 && (
          <div className="mb-2">
            <div className="space-y-0.5">
              {insights
                .filter((i) => i.type === 'link')
                .map((link) => (
                  <button
                    key={link.id}
                    onClick={() => handleInsightClick(link)}
                    className="block w-full text-left text-[8px] text-relic-slate/60 dark:text-relic-ghost/60 hover:text-relic-void dark:hover:text-white transition-colors font-mono"
                    title={link.content}
                  >
                    →{' '}
                    {typeof link.source === 'string' ? link.source : String(link.source || 'Link')}
                  </button>
                ))}
            </div>
            {/* Metacognitive Awareness */}
            {metacognition && (
              <div className="mt-2 pt-1.5 border-t border-relic-mist/10 dark:border-relic-slate/20">
                <div className="flex items-start gap-1.5">
                  <span className="text-[7px] text-relic-slate/40 dark:text-relic-ghost/50 font-mono">
                    {Math.round(metacognition.confidence * 100)}%
                  </span>
                  <p className="flex-1 text-[7px] text-relic-slate/50 dark:text-relic-ghost/60 italic font-mono leading-snug">
                    {metacognition.reasoning}
                  </p>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Compact Suggestion */}
        {insights
          .filter((i) => i.type === 'suggestion')
          .map((suggestion) => (
            <div key={suggestion.id} className="mb-2">
              <div className="text-[8px] text-relic-slate/50 dark:text-relic-ghost/60 font-mono leading-snug">
                {suggestion.content}
              </div>
            </div>
          ))}

        {/* Mini Chat Messages - Separate from main chat */}
        {miniChatMessages.length > 0 && (
          <div className="space-y-2 mb-3 max-h-[30vh] overflow-y-auto">
            {miniChatMessages.map((msg, idx) => (
              <div key={idx} className="space-y-1 group">
                <div className="flex items-center justify-between">
                  <div className="text-[7px] text-relic-void/70 dark:text-white/70 font-mono">
                    → {msg.query}
                  </div>
                  {onPromoteToMain && msg.response && msg.response !== '...' && (
                    <button
                      onClick={() => onPromoteToMain(msg.query, msg.response)}
                      className="text-[7px] text-relic-silver/30 dark:text-relic-ghost/30 hover:text-cyan-500 dark:hover:text-cyan-400 font-mono opacity-0 group-hover:opacity-100 transition-all"
                      title="Promote to main chat"
                    >
                      ↑main
                    </button>
                  )}
                </div>
                <div className="text-[7px] text-relic-slate/60 dark:text-relic-ghost/60 font-mono leading-snug pl-2">
                  {msg.response}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Minimal input */}
        <div className="mt-3 border-t border-relic-mist/10 dark:border-relic-slate/20 pt-2">
          <form onSubmit={handleSubmit} className="flex gap-1">
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder={isMiniLoading ? 'loading...' : 'query'}
              disabled={isMiniLoading}
              className="flex-1 px-2 py-1 text-[8px] font-mono bg-transparent text-relic-void dark:text-white placeholder:text-relic-silver/20 dark:placeholder:text-relic-ghost/30 focus:outline-none border-b border-relic-mist/10 dark:border-relic-slate/20 focus:border-relic-slate/20 dark:focus:border-relic-ghost/30 disabled:opacity-50"
            />
            <button
              type="submit"
              disabled={!inputText.trim() || isMiniLoading}
              className="text-[8px] font-mono text-relic-silver/40 dark:text-relic-ghost/40 hover:text-relic-void dark:hover:text-white disabled:text-relic-silver/10 dark:disabled:text-relic-ghost/10"
            >
              →
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
