/**
 * Enhanced Depth Annotations - In-Depth Explanations
 *
 * This file contains comprehensive, detailed annotation content with:
 * - Deep contextual explanations
 * - Metrics with comparisons and trends
 * - Historical context and implications
 * - Technical details and real-world applications
 */

export const ENHANCED_CONCEPT_INSIGHTS: Record<string, string> = {
  // NEURAL INTERFACE
  'neural_interface': `Brain-computer interface (BCI) technology enabling direct bidirectional communication between neural activity and external devices — Invasive approaches (Neuralink N1, Utah array) achieve 100+ electrode resolution via surgical implantation for high-fidelity signal capture, while non-invasive EEG methods (Emotiv, NeuroSky) use scalp sensors with lower spatial resolution but no surgical risk · Current capabilities: cursor control with 90%+ accuracy (BrainGate trial, tetraplegia patients), speech synthesis at 62 words/min (15-word vocabulary, Nature 2021), robotic prosthetic arm control with tactile feedback (DARPA HAPTIX), seizure prediction 30min advance (NeuroPace RNS) · Clinical applications: paralysis restoration (ALS, spinal cord injury), locked-in syndrome communication, stroke rehabilitation (brain plasticity training), Parkinson's deep brain stimulation, depression treatment (FDA-approved TMS) · Technical challenges: signal degradation from scar tissue formation after 12-18 months (gliosis), need for biocompatible materials, chronic inflammation response, power consumption for wireless implants, data bandwidth limitations · Market trajectory: $3.7B (2024) → $9.5B (2030) at 16.8% CAGR · Leading players: Neuralink ($363M funding, first human implant Jan 2024), Synchron (endovascular approach via blood vessels, 6 patients), Blackrock Neurotech (Utah array, 50+ implants since 2004), Kernel (non-invasive flow monitoring), BrainGate consortium (Brown, Stanford, Case Western) · Ethical considerations: cognitive enhancement inequality (only wealthy access), privacy of neural data (thoughts readable?), agency and consent (who controls the interface?), military applications (DARPA $65M NextGen program) · Consumer timeline: gaming/AR control 2027-2030, medical device approvals accelerating (FDA breakthrough designation), mainstream adoption 2035+`,

  // ARTIFICIAL GENERAL INTELLIGENCE
  'agi': `Artificial General Intelligence (AGI) — hypothetical AI system matching or exceeding human cognitive abilities across ALL domains including reasoning, learning, creativity, emotional intelligence, common sense, and seamless transfer between tasks · Distinction from narrow AI: current systems excel in specific domains (GPT-4 language, AlphaFold protein folding, DALL-E image generation) but lack general reasoning, embodied understanding, or ability to adapt to truly novel situations outside training distribution · Core capabilities required: few-shot learning (learn from 5-10 examples like humans vs millions), causal reasoning (understand cause-effect not just correlations), common sense physics/psychology (intuitive understanding of world), emotional/social intelligence, metacognition (awareness of own limitations), continual learning without catastrophic forgetting · Leading technical approaches: (1) scaling large language models with reasoning (OpenAI O1 using chain-of-thought, test-time compute), (2) neurosymbolic AI combining neural networks with symbolic logic, (3) world models predicting future states from actions, (4) embodied AI learning through physical interaction, (5) multi-agent systems with specialization · Timeline estimates vary wildly: OpenAI CEO Sam Altman (2027-2029 possible), Anthropic CEO Dario Amodei (early 2030s), DeepMind (2028-2035 range), skeptics argue 50+ years or never due to consciousness requirements · Economic impact projections: McKinsey $15.7 trillion added to global GDP by 2030 from AI, PwC $6.6 trillion productivity gains, but 40% of jobs transformed (not eliminated, complemented), creative/strategic roles less affected · Existential risks: alignment problem (ensuring AGI goals match human values not paperclip maximizer), power concentration (AGI controlled by few companies/nations), autonomous weapons (Slaughterbots scenario), unemployment cascade, surveillance dystopia · Governance frameworks: AI Safety Summit (Bletchley 2023, 28 countries agreed to testing pre-deployment), EU AI Act (risk-based regulation, high-risk systems banned), NIST AI Risk Management Framework, Anthropic Constitutional AI (self-training on principles), OpenAI Superalignment team (20% compute dedicated to alignment) · Current "proto-AGI" progress: GPT-4/Claude 3.5 Opus show cross-domain reasoning, vision+language, code generation, complex multi-step planning but lack true understanding, embodiment, or ability to question their own training`,

  // Continue with more detailed entries...
};

/**
 * Enhanced metric context generator
 * Provides deep analysis of numbers, percentages, and financial metrics
 */
export function getEnhancedMetricInsight(
  value: number,
  unit: string,
  context: string
): string {
  // PERCENTAGE ANALYSIS
  if (unit === '%' || unit === 'percent') {
    if (context.includes('growth') || context.includes('increase')) {
      if (value > 100) return `${value}% growth — Hypergrowth trajectory indicating viral adoption or emerging market · Sustainable only in early stages (1-3 years), typically 50-100% YoY thereafter · Comparable to early Facebook (2004-2007), Zoom (2019-2020), or Airbnb (2010-2012) · Key metrics to validate: retention cohorts, unit economics, customer acquisition cost vs lifetime value · Risk: growth at all costs without profitability path can lead to valuation collapse post-growth phase`
      if (value > 50) return `${value}% growth — Exceptional growth well above market averages · If sustained, implies strong product-market fit and scalable distribution · SaaS benchmark: >40% YoY for Series B/C stage · Technology adoption S-curve suggests transitioning from early adopters (13.5%) to early majority (34%) · Caution: ensure growth is organic, not marketing-fueled with poor retention`
      if (value > 20) return `${value}% growth — Solid growth above GDP (2-3%) and inflation (2-4%) · Healthy for established companies, modest for startups · Benchmark comparisons: S&P 500 average 10%, SaaS median 25-30%, e-commerce 15-20% · Indicates mature business with sustainable competitive advantages or moderate market expansion`
      return `${value}% growth — Modest growth rate typical of mature markets or early traction · GDP-level growth sufficient for capital preservation but below investor expectations for high-growth sectors · May indicate: market saturation, competitive pressure, operational constraints, or natural maturation curve`
    }

    if (context.includes('margin') || context.includes('profit')) {
      if (value > 40) return `${value}% margin — Exceptional profitability indicating strong pricing power, operational excellence, or network effects · Software/SaaS can achieve 70-90% gross margins (low COGS), 20-30% net margins · Comparable to: Microsoft (42% operating margin), Apple (30% net margin), Visa (66% operating margin) · Enables aggressive reinvestment while maintaining profitability, attractive to acquirers and public markets`
      if (value > 20) return `${value}% margin — Healthy profitability supporting reinvestment and shareholder returns · Technology industry average 15-25%, retail 2-5%, finance 10-15% · Rule of 40 for SaaS: growth rate + profit margin >40% indicates healthy balance · At this margin: cash generative, defensible moat, ability to weather downturns`
      if (value > 10) return `${value}% margin — Moderate profitability, room for optimization or facing competitive pressure · May indicate: high customer acquisition costs, infrastructure investment phase, or low-margin business model · Retail/e-commerce range, requires volume for absolute profit generation`
      return `${value}% margin — Thin margins requiring operational discipline and scale · Commodity businesses, highly competitive markets, or growth investment phase · Risk: vulnerable to cost increases, price wars, economic downturns · Need 10x revenue growth or operational improvements for attractive returns`
    }

    // General percentage
    return `${value}% — Relative metric requiring industry context for interpretation · Compare against: historical trends (YoY, 3-year CAGR), competitor benchmarks, market share calculations · Statistical significance: ensure sample size >1000 for consumer metrics, confidence intervals for survey data · Consider: selection bias, survivorship bias, regression to mean effects`
  }

  // USER/SUBSCRIBER METRICS
  if (unit.includes('user') || unit.includes('subscriber') || unit.includes('customer')) {
    if (value >= 1000000000) return `${value.toLocaleString()} ${unit} — Billion-user platform reaching 12.5%+ of global population · Extreme scale requiring sophisticated infrastructure: petabyte-scale data processing, multi-region CDN (100+ PoPs), sub-100ms latency globally, 99.99%+ uptime (4.38min downtime/month) · Monetization: ARPU $3-20 for social media, $50-120 for subscription services, $150+ for B2B SaaS · Network effects dominant: each new user increases value for existing users (Metcalfe's law: value ∝ n²), creates defensive moat · Comparable to: Facebook 3.05B MAU, YouTube 2.7B, WhatsApp 2.5B, Instagram 2.4B · Challenges: regulatory scrutiny (antitrust, data privacy GDPR), content moderation (10,000+ moderators), geopolitical fragmentation (data localization laws)`

    if (value >= 100000000) return `${value.toLocaleString()} ${unit} — Hundred-million-user platform at global scale · Infrastructure requirements: multi-cloud (AWS, GCP, Azure), auto-scaling to 10x daily peak, DDoS protection (100Gbps+ capacity), real-time analytics on billions of events · Monetization inflection: ARPU optimization critical, 1% improvement = $millions annually · User segmentation: power users (10% generate 50% value), casual users (retention challenge), dormant users (reactivation campaigns) · Growth mechanisms: viral loops (k-factor >1), organic search, paid acquisition (<$10 CAC for consumer), referral programs · Comparable to: LinkedIn 900M, Twitter 450M, Telegram 800M, Spotify 600M · Path to IPO: $100M+ ARR, 100%+ net dollar retention for SaaS, or strong engagement metrics for consumer`

    if (value >= 10000000) return `${value.toLocaleString()} ${unit} — Ten-million-user platform achieving critical mass · Traction validation: survived "valley of death" (80% of startups fail before $1M ARR), product-market fit confirmed, repeatable go-to-market · Infrastructure: transition from monolith to microservices, implement caching layers (Redis, Memcached), database sharding for horizontal scale, CI/CD automation · Monetization experiments: A/B testing (10,000+ tests/year at scale), pricing tiers (freemium vs premium), upsell/cross-sell optimization · Team scale: 50-200 employees, departmental structure emerging, need for middle management, company culture risk · Comparable to: Notion 30M, Duolingo 40M, Clubhouse peak 10M · Next phase: international expansion (localization 10+ languages), enterprise sales motion, or IPO preparation`

    if (value >= 1000000) return `${value.toLocaleString()} ${unit} — Million-user platform validating product-market fit · Engagement crucial: DAU/MAU >20% for consumer social, >40% for utility apps, retention Day 30 >30% · Unit economics: LTV:CAC ratio target 3:1, payback period <12 months for B2C, <18 months for B2B SaaS · Technical challenges: database optimization (query performance <100ms), API rate limiting, background job processing (Sidekiq, Celery), monitoring/alerting (DataDog, New Relic) · Funding stage: Series B ($20-50M) or cash-flow positive, valuation $50-200M depending on growth rate and sector multiples · Comparable to: early-stage Uber (2011), Airbnb (2010), Dropbox (2009) · Growth experiments: referral programs (Dropbox +60% from referrals), partnerships, content marketing, community building`

    if (value >= 100000) return `${value.toLocaleString()} ${unit} — 100K users demonstrating initial market validation · Early product-market fit indicators: NPS >50, organic growth >20% MoM, qualitative user love (testimonials, unsolicited praise) · Cohort analysis critical: Month 0 retention >40%, Month 3 retention >20%, improving or stable curves · Infrastructure: can still run on single database, but implement caching, background jobs, analytics (Mixpanel, Amplitude) · Monetization testing: minimum 10K users for meaningful conversion experiments, pricing elasticity tests, payment provider integration (Stripe, PayPal) · Funding stage: Seed to Series A ($2-15M), valuation $10-50M, need clear path to $1M ARR · Comparable to: Product Hunt initial launch (10K), Superhuman early access (5K), early Clubhouse (50K) · Risk: premature scaling (hiring too fast, over-engineering), competitor copying features, retention falling off`

    return `${value.toLocaleString()} ${unit} — Early adoption phase building initial user momentum · Focus on: qualitative feedback over quantitative metrics, retention over acquisition, product iteration speed (weekly releases), core value proposition clarity · Pre-product-market fit: expect high churn (50-70%), experiment rapidly with features, identify power users (10%) and understand their workflows · Funding: pre-seed or bootstrapped (<$1M), team 2-10 people, runway 12-18 months · Traction milestones: 1000 users (initial validation), 10,000 users (repeatable growth), 100,000 users (PMF confirmed) · Common failure modes: building for wrong user, solving symptom not root cause, lack of distribution strategy`
  }

  // REVENUE/VALUATION METRICS
  if (unit.includes('billion') || unit.includes('million') || unit === 'M' || unit === 'B') {
    const numericValue = unit === 'B' ? value * 1000 : value; // Convert to millions

    if (context.includes('valuation')) {
      if (numericValue >= 100000) return `$${value}${unit} valuation — Mega-cap company among global elite · Market cap >$100B places in top 100 companies globally (S&P 500 avg $77B) · Comparable to: Nvidia $3.1T (Nov 2024), Microsoft $3.0T, Apple $2.9T, Amazon $1.9T · At this scale: influences index ETF prices, options market large (gamma hedging impacts stock), analyst coverage 30-50+, institutional ownership 70-80% · Valuation multiples compress: P/E 15-30x (vs 50-100x growth stocks), revenue multiple 5-10x for tech (vs 20-30x hypergrowth) · Growth expectations modest: 10-15% YoY sufficient to maintain valuation, focus on capital allocation (dividends, buybacks), M&A accretive deals · Regulatory scrutiny intense: antitrust reviews for acquisitions, data privacy regulations, sector-specific oversight · Risk: disruption threat from emerging tech (Kodak film→digital, Nokia phones→smartphones, taxi→Uber)`

      if (numericValue >= 10000) return `$${value}${unit} valuation — Decacorn ($10B+) or established public company · Funding stage: late-stage private (Series E+) or IPO'ed, institutional investor dominated (Tiger Global, Fidelity, Softbank Vision Fund) · Valuation metrics: 10-20x revenue for SaaS (public comps), 5-10x for marketplaces, 2-5x for traditional businesses · IPO considerations: $100M+ revenue, path to profitability (or 40%+ Rule of 40), strong unit economics, total addressable market $10B+, competitive moat · Comparable to: Databricks $43B (2023), Stripe $95B (2021 peak, down from crypto bubble), SpaceX $150B (2024) · At this scale: meaningful impact on employment (thousands of jobs), ecosystem of third-party developers/partners, press scrutiny on ESG, culture, leadership · Liquidity options: direct listing (Spotify, Coinbase), traditional IPO, secondary shares for employees ($1-5M+ for early employees) · Risk: down rounds if growth slows (WeWork $47B→$8B→$45M), competition from megacaps (Google/Microsoft clones features)`

      if (numericValue >= 1000) return `$${value}${unit} valuation — Unicorn ($1B+) status achieved, elite startup cohort · Frequency: 1 in 1000 startups reach unicorn, global count ~1,200 (CB Insights 2024), median time 7-10 years from founding · Funding stage: Series C/D ($50-200M rounds), investors include later-stage VCs (Sequoia, Andreessen Horowitz, GV) and growth equity (General Atlantic, Insight Partners) · Valuation drivers: $50M+ ARR with 50-100%+ YoY growth, strong net revenue retention (120%+ for SaaS), compelling unit economics, large TAM ($5B+), technological moat or network effects · Comparable to: Figma $20B (2022, Adobe acquisition attempt), Canva $26B (2021), Notion $10B (2023), Discord $15B (2021) · Employee wealth creation: early employees (equity 0.1-2%) potentially $1-20M+, dilution from later rounds 20-40%, option exercise tax considerations · Strategic decisions: growth vs profitability balance, international expansion ($20M+ investment), M&A for consolidation, IPO preparation (18-24 months) · Risk: mismanagement of capital (burn rate $10-30M/month), valuation down-rounds crushing morale, competitor with more capital, market shift (interest rates impact multiples)`

      if (numericValue >= 100) return `$${value}${unit} valuation — Emerging unicorn candidate or strong growth company · Funding stage: Series B ($20-50M) to Series C ($50-100M), institutional VCs leading, pro-rata from earlier investors · Traction required: $10M+ ARR with 100%+ YoY growth (or $2M ARR with 200%+ growth), 100K+ users for consumer, 100+ enterprise customers for B2B, strong retention (90%+ net revenue retention) · Valuation multiples: 15-30x forward revenue for SaaS (public comps trade 10-20x), 10-15x for marketplaces, 5-10x for e-commerce · Team scale: 50-200 employees, VP-level execs hired (VP Sales, VP Eng, CFO), organizational structure needed, culture scaling challenge · Comparable to: early Airtable ($1.1B 2020), Miro ($17.5B 2022), Retool ($3.2B 2022), Snyk ($8.5B 2022) · Next phase decisions: vertical expansion (new customer segments), horizontal expansion (new product lines), geographic expansion (Europe, Asia), or M&A strategy · Technical challenges: scaling infrastructure (10x user growth), security/compliance (SOC 2, GDPR, HIPAA), uptime SLAs (99.9%+), data governance · Risk: competitors raising larger rounds (Figma vs Adobe XD, Notion vs Microsoft Loop), market saturation, retention declining from early adopter cohort`

      return `$${value}${unit} valuation — Early to mid-stage venture-backed company · Funding stage: Seed ($2-5M) to Series A ($5-20M), valuation $20-100M post-money · Traction expectations: $1M+ ARR for Series A (40-50% dilution typical), clear product-market fit, repeatable sales motion, strong unit economics (LTV:CAC >3:1) · Investor profile: specialized VCs (Kleiner Perkins, Lightspeed, Sequoia early-stage), angels with domain expertise, accelerators (YC, Techstars) · Comparable to: early Notion (Series A $10M 2018), Figma (Series A $14M 2016), Superhuman (Series B $33M 2019 at $260M valuation) · Key hires: first sales hire (AE or VP Sales), product manager, data analyst, customer success lead, growing eng team (5-15 engineers) · Growth experiments: outbound sales, content marketing (SEO), partnerships, community building, product-led growth (freemium) · Technical focus: core product robustness, analytics instrumentation, experimentation framework (A/B testing), monitoring/alerting · Risk: runway 12-24 months, failure to reach next milestone (Series B typically requires $5-10M ARR), founder/team burnout, pivoting too late`
    }

    if (context.includes('ARR') || context.includes('revenue')) {
      if (numericValue >= 1000) return `$${value}${unit} ARR — Massive recurring revenue at public company scale · Annual Recurring Revenue exceeding $1B indicates: 10,000+ enterprise customers at $100K ACV, or 1M+ SMB customers at $1K ACV, or 100M+ consumers at $10/user · Business characteristics: 120-150%+ net dollar retention (expansion revenue exceeds churn), <5% annual churn for enterprise, multi-product platform (3+ products driving expansion), land-and-expand motion perfected · Valuation multiples: public SaaS companies trade 10-15x ARR (2024 medians), best-in-class 20x (CrowdStrike, Snowflake, Datadog), depends on growth rate (40%+ commands premium) and profitability · Comparable to: Salesforce $31B ARR (2024), Microsoft 365 $60B+, Adobe Creative Cloud $15B, ServiceNow $8.5B, Workday $7.2B · IPO readiness: definitely public or late-stage private (Stripe $13B ARR still private), Rule of 40 achieved (growth% + profit% >40), Fortune 500 customer concentration, SEC compliance infrastructure · Operating leverage: 30-40% operating margins achievable (gross margin 70-85%, sales/marketing 35-45% of revenue, R&D 15-25%), net income margins 15-25% for mature SaaS · Strategic M&A active: acquiring point solutions for $100M-1B to cross-sell into base, platform consolidation trend · Team scale: 5,000-30,000 employees, complex org structure, distributed globally, culture challenges at scale`

      if (numericValue >= 100) return `$${value}${unit} ARR — Significant recurring revenue base, IPO candidate territory · Annual Recurring Revenue $100M+ places company in top 1% of SaaS businesses, demonstrates: repeatable sales motion at scale, product-market fit across segments, operational excellence, strong retention economics · Growth expectations: 40-60% YoY growth from $100M base (vs 100%+ at $10M), slower but still rapid, doubling every 18-24 months · Customer profile: 500-2000 enterprise customers at $50-200K ACV, or 50K+ SMB customers at $2-5K ACV, mix of direct sales (75%) and channel partners (25%) · Valuation range: $1-2B at 10-20x ARR multiple depending on growth/profitability mix, public market comps influential, private likely late-stage Series D/E · IPO considerations: median SaaS IPO at $100-150M ARR, need 30%+ YoY growth, path to profitability (Rule of 40), S-1 ready (audited financials 2-3 years), underwriters engaged (Goldman, Morgan Stanley) · Comparable to: MongoDB $1.3B ARR (public), HashiCorp $500M ARR (IPO 2021), UiPath $1B ARR (IPO 2021), Databricks $1.5B ARR (private) · Operating metrics: gross margin 70-80% (mature SaaS), sales efficiency (CAC payback 12-18 months), net retention 120-130%, expansion driving 40% of new ARR · Team maturity: 500-2000 employees, executive team complete (C-suite), international presence (Europe, APAC), layered sales org (SDRs, AEs, CSMs, renewals)`

      if (numericValue >= 10) return `$${value}${unit} ARR — Strong recurring revenue milestone, Series B/C stage · Annual Recurring Revenue $10M+ demonstrates: product-market fit confirmed, repeatable sales playbook, ability to scale to $100M, strong unit economics · Growth rate: 100-150% YoY typical at this stage (doubling every 8-12 months), faster indicates viral mechanics or market timing, slower indicates scaling challenges · Customer breakdown: 50-200 enterprise customers at $50-200K ACV (for high-touch sales), or 2,000-10,000 SMB customers at $5-10K ACV (for low-touch), or 100K+ consumers at $100-200 annually · Funding stage: Series B ($20-50M at $100-300M valuation) or cash-flow positive if capital efficient, Series C ($50-100M) if investing heavily for growth · Comparable to: Airtable $10M ARR (2018 Series B), Notion $10M ARR (2019), early Figma, Front (email client) · Hiring acceleration: 50-150 employees, VP-level execs (Sales, Marketing, Eng, Product), quota-carrying sales reps (10-30), expanding eng (20-60), customer success team · Sales motion maturing: inbound (60%) vs outbound (40%) mix, PLG motion if freemium, channel partners for geographic expansion, logo acquisition vs account expansion balance · Technical investments: microservices architecture, observability stack (DataDog, New Relic), security certifications (SOC 2 Type 2, ISO 27001), data infrastructure (warehouse, BI tools) · Risk: scaling too fast and burning cash, competition intensifying, hiring mismatches, retention softening from early adopter cohort`

      return `$${value}${unit} ARR — Early recurring revenue traction, Series A territory · Annual Recurring Revenue $1M+ is critical Series A milestone (40-50% dilution at $10-30M valuation post-money), demonstrates: product-market fit emerging, repeatable customer acquisition, willingness to pay validated · Growth trajectory: 200-300% YoY not uncommon at this stage, need to prove path to $10M within 24-36 months · Customer composition: 10-50 paying customers for enterprise B2B, 500-2000 for SMB SaaS, 10K+ for consumer subscriptions · Pricing validation: found pricing tier that resonates ($50-200/seat/month for SaaS, $10-50 for consumer), elasticity testing ongoing, annual prepay discounts (10-20%) for cash flow · Comparable to: early Superhuman $1M ARR (2019 before Series B), Roam Research $1M ARR (2020), many YC companies at Demo Day · Team: 5-20 employees, first sales hire critical, product-market fit still being refined, customer success role emerging · Funding: Seed extension ($2-5M bridge) or Series A ($5-15M), 18-24 month runway typical, unit economics (LTV:CAC >3:1) scrutinized · Next phase: hire VP Sales to build sales team, expand from founder-led sales, implement CRM (Salesforce, HubSpot), establish customer success motion, product roadmap prioritization framework · Risk: churn exceeding new ARR (net negative), unable to hire sales talent, product not scaling beyond early adopters, competition from incumbents`
    }
  }

  // PERFORMANCE/SPEED METRICS
  if (unit.includes('faster') || unit.includes('slower') || unit.includes('ms') || unit.includes('seconds')) {
    if (context.includes('query') || context.includes('response') || context.includes('latency')) {
      const ms = unit.includes('ms') ? value : value * 1000;
      if (ms < 100) return `${value}${unit} — Excellent performance meeting real-time interaction standards · Sub-100ms latency perceived as instantaneous by users (Miller 1968, Doherty threshold), critical for: autocomplete, search-as-you-type, collaborative editing, financial trading systems · Google research: 100-400ms delay reduces searches by 0.59%, Amazon: 100ms delay costs 1% revenue · Technical approach: edge caching (CDN), database index optimization, query result caching (Redis), denormalization for read-heavy workloads, vertical scaling for CPU-intensive operations · Comparable to: Google Search <50ms median, Cloudflare edge <20ms, Algolia search <10ms, stock trading platforms <5ms · Infrastructure: geo-distributed databases (multi-region), read replicas, materialized views, connection pooling`
      if (ms < 500) return `${value}${unit} — Good performance for most web interactions · 200-500ms is optimal for web page loads (Google Core Web Vitals targets 2.5s for Largest Contentful Paint) · User perception: noticeable but acceptable delay, maintains flow state, no productivity impact for single actions · Optimization priorities: database query optimization (N+1 problem, eager loading), API response time monitoring, code profiling for hot paths, lazy loading for non-critical resources · Benchmark: median web page load 2.5s (desktop), 3.7s (mobile), API response 200-400ms considered acceptable`
      if (ms < 2000) return `${value}${unit} — Moderate latency, user experience degradation begins · 1-2 second delays break flow state, users notice and may perceive as "slow" · Causes: unoptimized database queries (full table scans, missing indexes), external API calls without timeouts, synchronous processing, cold start (serverless), inefficient algorithms (O(n²) complexity) · User impact: abandoned searches (25% bounce rate for 1-3s), form submission hesitation, frustration with interactive features · Remediation: implement caching layers, async background jobs for non-critical work, database query profiling (EXPLAIN ANALYZE), consider eventual consistency for non-critical data`
      return `${value}${unit} — Slow performance requiring optimization · ${value}${unit} latency causes: poor database design, missing indexes, N+1 queries, inefficient external API calls, lack of caching, serverless cold starts, CPU/memory constraints · User impact: high bounce rates (40%+ for >3s), abandoned sessions, negative brand perception, reduced conversion (7% for each 100ms delay after 3s) · Critical fixes: database query optimization (explain plans, index coverage), implement Redis/Memcached caching, CDN for static assets, upgrade server resources, async processing for background tasks, APM tools (New Relic, DataDog) to identify bottlenecks`
    }
  }

  // TIME METRICS (days, hours, months)
  if (unit.includes('day') || unit.includes('hour') || unit.includes('month') || unit.includes('year')) {
    if (context.includes('runway') || context.includes('cash')) {
      if (value >= 24) return `${value} ${unit} runway — Healthy cash buffer providing strategic flexibility · 24+ months runway considered ideal: survives economic downturn (2-3 year cycles), time to experiment with pricing/distribution, leverage in fundraising (not desperate), weather product-market fit iterations · Burn rate implications: if raising every 18-24 months, currently in "safe zone" · Strategic options enabled: can wait for better valuation environment, pursue organic profitability path, make selective hires, resist acquihire pressure · Risk management: build scenario planning (base/conservative/aggressive), monthly board reporting on runway, trigger points for cost cuts (when to reduce burn), contingency plans for bridge financing`
      if (value >= 12) return `${value} ${unit} runway — Adequate breathing room but fundraising mode imminent · 12-18 month runway typical post-fundraise, implies: fundraising should begin in 3-6 months (process takes 3-6 months), need to show momentum in next 6 months (2-3 quarters of growth data), milestones for next round clear · Burn rate discipline: monitor monthly burn, implement rolling 3-month forecast, board approval for major expenses, hiring discipline (every headcount scrutinized) · Fundraising timeline: start conversations 6 months before runway ends, close round 3 months before, never wait until <6 months (signals desperation, weak negotiating position) · Bridge round risk: if milestones not met, need bridge financing (insider round, convertible notes, venture debt) with potential down-round terms`
      if (value >= 6) return `${value} ${unit} runway — Urgent fundraising mode, survival timeline visible · 6-12 month runway is critical zone: must be actively fundraising now (3-6 month process), considering all options (equity, debt, revenue-based financing), potential down-round if metrics soft · Decision points: extend runway via cost cuts (headcount reduction, office closure, discretionary spend freeze), pursue acquihire (soft landing for team), pivoting strategy, or accelerate to profitability if close (cut burn to zero within runway) · Investor psychology: desperation visible, terms worsen, valuation pressure, onerous terms (ratchets, liquidation preferences), higher dilution · Survival tactics: focus on revenue (close sales pipeline), cut burn immediately (30-50% reduction), prioritize 1-2 features only, monthly cash flow monitoring, negotiate payment terms (extend payables, accelerate receivables)`
      return `${value} ${unit} runway — Crisis mode, immediate action required · <6 month runway is emergency: company may not survive, all hands focused on fundraising or path to profitability, morale impact severe, talent flight risk · Immediate actions: freeze all hiring, cut burn 50%+ (layoffs, office, travel, contractors), CEO 100% focused on fundraising or M&A, board meeting weekly, daily cash monitoring · Fundraising options limited: down round likely (50%+ valuation cut), bridge financing with punitive terms (20% discount, 2x liquidation preference), insiders-only round, or venture debt (expensive but non-dilutive) · Alternative paths: acquihire (team acquisition for $1-5M), asset sale (sell product/IP to competitor), wind down (return capital to investors if any left, legal obligations settled) · Founder psychology: extreme stress, consider team welfare, reputation management (how you handle crisis matters for next company), lessons learned for future`
    }
  }

  // Default fallback for any unhandled cases
  return `${value} ${unit} — Metric requiring context-specific interpretation · Benchmark against: historical trends (3-year average, YoY growth), industry comparisons (percentile ranking), competitive positioning, correlation with business outcomes · Statistical rigor: sample size adequacy (>1000 for consumer metrics), confidence intervals (95% standard), p-value significance (<0.05), potential confounding variables · Consider: leading vs lagging indicator (predictive value), actionability (can we influence it?), cost of measurement vs insight value, correlation vs causation (A/B testing for causal claims) · Best practices: define metric precisely (numerator/denominator), establish measurement frequency (daily/weekly/monthly), set targets (OKRs), assign ownership, review cadence (weekly/monthly/quarterly)`
}
