'use client'

import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-relic-white dark:bg-relic-void py-20 px-6">
      <div className="max-w-2xl mx-auto font-mono">
        <Link href="/" className="text-[10px] text-relic-silver hover:text-relic-slate mb-8 block">← back</Link>
        <h1 className="text-2xl font-light text-relic-void dark:text-white mb-2">Terms of Use</h1>
        <p className="text-[10px] text-relic-silver mb-8">Last updated: March 2026</p>

        <div className="space-y-6 text-sm text-relic-slate dark:text-relic-ghost leading-relaxed">
          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">Service</h2>
            <p>AkhAI is a sovereign AI research engine currently in early access (family &amp; friends). The service is provided as-is. Features, availability, and pricing may change without notice during this phase.</p>
          </section>

          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">Usage</h2>
            <p>You agree to use AkhAI for lawful purposes only. Do not submit queries intended to generate harmful, illegal, or abusive content. We reserve the right to suspend accounts that violate this policy.</p>
          </section>

          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">AI-Generated Content</h2>
            <p>Responses are generated by AI models and may contain errors, hallucinations, or outdated information. AkhAI is a research tool, not a source of truth. Always verify important information independently. We are not liable for decisions made based on AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">Intellectual Property</h2>
            <p>The AkhAI platform, Sefirot architecture, Sovereign Guard system, and related technologies are proprietary. Open-source components are released under Apache 2.0 as specified in our repository.</p>
          </section>

          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">Limitation of Liability</h2>
            <p>AkhAI is provided without warranty. We are not liable for any damages arising from use of the service, including but not limited to data loss, service interruption, or reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xs uppercase tracking-widest text-relic-silver mb-2">Contact</h2>
            <p>Questions: algoq2039@proton.me</p>
          </section>
        </div>
      </div>
    </div>
  )
}
