import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/database';
import { getUserFromSession } from '@/lib/auth';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format') || 'md';
  const { id: queryId } = await params;

  try {
    const token = request.cookies.get('session_token')?.value;
    const user = token ? getUserFromSession(token) : null;
    const userId = user?.id ?? null;

    const query = db.prepare('SELECT * FROM queries WHERE id = ?').get(queryId) as
      | {
          id: string;
          query: string;
          flow: string;
          status: string;
          tokens_used: number | null;
          cost: number | null;
          result: string | null;
          created_at: number;
          user_id: string | null;
        }
      | undefined;
    if (!query) return NextResponse.json({ error: 'Query not found' }, { status: 404 });

    // Ownership scope (E4.2b): a row owned by someone (user_id set) is exportable only by
    // that someone. Anonymous/legacy rows (user_id null) stay exportable. Return the SAME
    // 404 as a missing row — a 403 would leak that the id is valid.
    if (query.user_id !== null && query.user_id !== userId) {
      return NextResponse.json({ error: 'Query not found' }, { status: 404 });
    }

    const events = db
      .prepare('SELECT type, data, timestamp FROM events WHERE query_id = ? ORDER BY id ASC')
      .all(queryId) as Array<{ type: string; data: string; timestamp: number }>;

    if (format === 'md') {
      const markdown = generateMarkdown(query, events);
      return new NextResponse(markdown, {
        headers: {
          'Content-Type': 'text/markdown',
          'Content-Disposition': `attachment; filename="akhai-query-${queryId}.md"`,
        },
      });
    }

    if (format === 'json') return NextResponse.json({ query, events });

    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}

interface ExportQueryRow {
  id: string;
  query: string;
  flow: string;
  status: string;
  tokens_used: number | null;
  cost: number | null;
  result: string | null;
  created_at: number;
}
interface ExportEventRow {
  type: string;
  data: string;
  timestamp: number;
}

function generateMarkdown(query: ExportQueryRow, events: ExportEventRow[]): string {
  const date = new Date(query.created_at * 1000).toISOString();

  let md = `# AkhAI Query Report\n\n`;
  md += `**Query ID:** ${query.id}\n`;
  md += `**Date:** ${date}\n`;
  md += `**Flow:** ${query.flow}\n`;
  md += `**Status:** ${query.status}\n`;
  md += `**Tokens Used:** ${query.tokens_used?.toLocaleString() || 'N/A'}\n`;
  md += `**Cost:** $${query.cost?.toFixed(4) || '0.00'}\n\n`;
  md += `## Query\n\n${query.query}\n\n`;

  const advisorResponses: Array<{ family: string; slot: number; response: string }> = [];
  let redactorOutput = '';
  let finalDecision = '';

  events.forEach((e) => {
    const data = JSON.parse(e.data || '{}');
    if (e.type === 'advisor-complete') advisorResponses.push(data);
    else if (e.type === 'redactor-complete') redactorOutput = data.output;
    else if (e.type === 'mother-base-review') finalDecision = data.decision;
  });

  if (advisorResponses.length > 0) {
    md += `## Advisor Responses\n\n`;
    advisorResponses.forEach(
      (r) => (md += `### ${r.family} (Slot ${r.slot})\n\n${r.response}\n\n`)
    );
  }

  if (redactorOutput) md += `## Redactor Synthesis\n\n${redactorOutput}\n\n`;
  if (finalDecision) md += `## Final Decision\n\n${finalDecision}\n\n`;
  if (query.result) {
    try {
      const resultObj = JSON.parse(query.result);
      md += `## Result\n\n${resultObj.finalDecision || query.result}\n\n`;
    } catch {
      md += `## Result\n\n${query.result}\n\n`;
    }
  }

  md += `---\n*Generated by AkhAI on ${new Date().toISOString()}*\n`;
  return md;
}
