import { NextResponse } from 'next/server';
import { db } from '@/lib/database';

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format') || 'md';
  const { id: queryId } = await params;

  try {
    const query = db.prepare('SELECT * FROM queries WHERE id = ?').get(queryId) as any;
    if (!query) return NextResponse.json({ error: 'Query not found' }, { status: 404 });

    const events = db.prepare('SELECT type, data, timestamp FROM events WHERE query_id = ? ORDER BY id ASC').all(queryId) as any[];

    if (format === 'md') {
      const markdown = generateMarkdown(query, events);
      return new NextResponse(markdown, {
        headers: {
          'Content-Type': 'text/markdown',
          'Content-Disposition': `attachment; filename="akhai-query-${queryId}.md"`,
        },
      });
    }

    if (format === 'json') return NextResponse.json({ query, events });

    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}

function generateMarkdown(query: any, events: any[]): string {
  const date = new Date(query.created_at * 1000).toISOString();

  let md = `# AkhAI Query Report\n\n`;
  md += `**Query ID:** ${query.id}\n`;
  md += `**Date:** ${date}\n`;
  md += `**Flow:** ${query.flow}\n`;
  md += `**Status:** ${query.status}\n`;
  md += `**Tokens Used:** ${query.tokens_used?.toLocaleString() || 'N/A'}\n`;
  md += `**Cost:** $${query.cost?.toFixed(4) || '0.00'}\n\n`;
  md += `## Query\n\n${query.query}\n\n`;

  const advisorResponses: any[] = [];
  let redactorOutput = '';
  let finalDecision = '';

  events.forEach(e => {
    const data = JSON.parse(e.data || '{}');
    if (e.type === 'advisor-complete') advisorResponses.push(data);
    else if (e.type === 'redactor-complete') redactorOutput = data.output;
    else if (e.type === 'mother-base-review') finalDecision = data.decision;
  });

  if (advisorResponses.length > 0) {
    md += `## Advisor Responses\n\n`;
    advisorResponses.forEach(r => md += `### ${r.family} (Slot ${r.slot})\n\n${r.response}\n\n`);
  }

  if (redactorOutput) md += `## Redactor Synthesis\n\n${redactorOutput}\n\n`;
  if (finalDecision) md += `## Final Decision\n\n${finalDecision}\n\n`;
  if (query.result) {
    try {
      const resultObj = JSON.parse(query.result);
      md += `## Result\n\n${resultObj.finalDecision || query.result}\n\n`;
    } catch {
      md += `## Result\n\n${query.result}\n\n`;
    }
  }

  md += `---\n*Generated by AkhAI on ${new Date().toISOString()}*\n`;
  return md;
}
